### ISSUE TITLE
some code improvement required and high resource usage in a short time.

### ISSUE THREAD

**Issue by zhaolun7** [zivlab/CellReg#17]
`nansum` is not availble in matlab 2022a, use sum(xx , 'omitnan') to replace two places.
![image](https://user-images.githubusercontent.com/16096787/195707172-361a6056-52cf-4583-a95d-6d7cfce63269.png)

When I run with sample, I observe a high resource usage:
![image](https://user-images.githubusercontent.com/16096787/195707243-d4faed84-ade2-4aca-9531-48b3dcad7799.png)

and in step 2, if I choose 'translation' it will fail:
![image](https://user-images.githubusercontent.com/16096787/195707533-42017e44-f6c6-4603-9d2e-130958b490c1.png)
![image](https://user-images.githubusercontent.com/16096787/195707878-4c9e6a6b-e33d-441c-b0c3-c4f3506ed6a0.png)

**Comment by Sheintuch** [comment]
Hi. Thank you for noticing these errors and opening this issue. 
1. I changed the nansum to sum('omitnan') so that CellReg will work for matlab 2022a (see new CellReg version v1.5.3).
2. I fixed the error of unrecognized variable 'unrotated_spatial_footprints' and now you can choose 'translations' in the alignment type without running into an error.
3. Regarding the high resource usage - is that a problem that causes an error? Does it interfere with working on other things at the same time with your computer? This would probably require a significant change in the code in order to fix. Did you have a specific suggestion in mind?

**Comment by zhaolun7** [comment]
@Sheintuch Thank you for the fix. My computer have 32g memory so this procedure works well. But it may be unfriendly to other lower memory pc. I haven't looked closely at the implementation details, but I'm surprised that running through the sample data uses so much memory. Thanks again for your fixing other problems.

**Comment by zhaolun7** [comment]
![image](https://user-images.githubusercontent.com/16096787/197059113-f93c4967-0c8d-4a13-9557-b86a8231d89a.png)
if I choose 'translate' only, it works well in step 2, but next step(step 3) meet error.........

**Comment by Sheintuch** [comment]
I am running the script with only translations and can go over all of the steps without encountering any error.
Are you sure you correctly updated to the new version? Did you use the git pull command or did you download the repository again? If you downloaded the repository, did you make sure you delete the older version from your computer?

**Comment by zhaolun7** [comment]
In step 3, it do ouput the result. but I see a error message in control concole. it may means something wrong..
![image](https://user-images.githubusercontent.com/16096787/197225042-380b3d22-a1c6-4048-b122-73307e3f20a7.png)
I delete the old code, download a new zip file from github. then run `CellReg_setup.m`
![image](https://user-images.githubusercontent.com/16096787/197225342-136d7d18-2df4-43b4-9f83-cc501e3f6988.png)
and I compare the difference. It's same with the version 1.5.3
![image](https://user-images.githubusercontent.com/16096787/197226159-b4bd6c2c-0331-4a67-bd9f-050dd12a0e3f.png)

**Comment by Sheintuch** [comment]
From the error message you posted here it seems that it is happening in step 2 when trying to save the results (otherwise you would see in the command window that it finished with aligning the sessions). Can you see if this is correct and that indeed you see this error in the command window even without starting step 3?

I am not sure why this happening as I am not getting this error. Just to make sure, the only thing you are changing from the default parameters is the choice of 'translations' in the alignment type? And other than that, you simply load new data in step 1, set the microns per pixel and then press the align images button?

**Comment by zhaolun7** [comment]
In step 2 it may open something like a thread pool to accelerate calculation(I am new to matlab). I don't notice that, and start step 3 before step 2 is finished. now it works ok. Thank you for the information.

**Comment by Sheintuch** [comment]
Hi. Thank you for the advice. 
There is an option for users not to use the parallel processing if you are running CellReg through the 'demo' script instead of the GUI. You will need to change the 'use_parallel_processing' variable in line 75 in the 'demo' script from true to false.
Let me know if this solves the high memory requirement issue for you and if you need it also for the GUI. If you do need it specifically for the GUI, I will work on adding this feature as a checkbox.
