### ISSUE TITLE
Using different microns/pixel for each axis

### ISSUE THREAD

**Issue by xwchia** [zivlab/CellReg#5]
Hi! Thank you for building this wonderful toolbox.

I'm trying my data on this CellReg, and i was wondering if it supports using different microns/pixel for the x and y axis. I.e. X: 1um/pixel, Y: 2.5um/pixel.

I tried inputing two values, but it failed aligning.

Wondering if theres any way to implement this? And if it is not possible, should i then manually adjust my input data (spatial footprint)?

Thank you.

**Comment by Sheintuch** [comment]
Hello, 

In its current version, CellReg does not support using different microns/pixel for the x and y axis. 
It is possible to implement it, but I'm not sure how simple it would be. 
How were you thinking about adjusting your input? By down-sampling the data in the x axis by a factor of 2.5?
If so, I think it would be the simplest solution, and since for 1-photon data there is no real need for higher spatial resolution than 2.5 microns it should not decrease the accuracy of your registration.  

Let me know what you think.

**Comment by xwchia** [comment]
Thank you for your reply! I'm using 2-photon data, so i'm abit wary about the spatial resolution. I'm currently just trying to use 1um/pixel for both X and Y and trying to validate manually if the cells matched are correct.

I couldn't find it in the wiki, but is there any way of inspecting the matched cells after aligning them via CellReg? If not, i'm also trying to use the "cell_registered_struct.centroid_locations_corrected" to crop the cells from my image.

Thanks!

**Comment by Sheintuch** [comment]
There is no manual inspection. 
Would  you like to send me the files with the spatial footprints you are trying to register via e-mail/slack?
So I can understand more how this issue affects registration quality.
